version: '3.8'

services:
  # 1. Redis
  redis:
    image: redis:alpine
    container_name: news-and-podcast-redis
    ports:
      - "6379:6379"

  # 2. FastAPI Uygulaması
  api:
    build: .
    container_name: news-and-podcast-api
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - redis

  # 3. Amele Celery Worker: Sadece uzun süren scraper işlerini yapar
  scraper-worker:
    build: .
    container_name: news-and-podcast-scraper-worker
    command: celery -A worker.celery_app worker --loglevel=info --concurrency=1 -Q scraper_queue # 1 tane worker çalıştır, böylece scraper'ın eşzamanlı çalışması engellenir. 1'den fazla çalışırsa .scraper_seen_urls.json dosyasına aynı url'ler yazılabilir ve bu da scraper'ın verimsiz çalışmasına neden olabilir.
    env_file: 
      - .env
    volumes:
      - .:/app  # Kodları ve scraper hafızasını bilgisayarla senkronize eder
    depends_on:
      - redis

  # 4. VIP Worker: Podcast isteklerini anında yakalar
  ai-worker:
    build: .
    container_name: news-and-podcast-ai-worker
    command: celery -A worker.celery_app worker --loglevel=info --concurrency=4 -Q ai_queue
    env_file: 
      - .env
    depends_on:
      - redis

  # 5. React Frontend
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - api