version: '3.8'

services:
  # Senin FastAPI Uygulaman
  api:
    build: .  # Aynı dizindeki Dockerfile'ı kullanarak imajı oluşturur
    container_name: news-and-podcast-api
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"